apply plugin: 'org.openapi.generator'

tasks.register('getExamples') {
  doLast {
    ant.property(name: "srcUrl",
                value: "https://raw.githubusercontent.com/couchbase/cbft/refs/heads/morpheus/docs/spec/manage/examples")
    ant.echo("Fetching from ${ant.srcUrl}")
    ant.get(dest: "examples", ignoreerrors: "true") {
      ant.url(url: "${ant.srcUrl}/file-xfer-200.json")
      ant.url(url: "${ant.srcUrl}/file-xfer-405.json")
      ant.url(url: "${ant.srcUrl}/file-xfer-disable.sh")
      ant.url(url: "${ant.srcUrl}/file-xfer-enable.sh")
    }
  }
}

openApiGenerate {
    generatorName = "asciidoc"
    remoteInputSpec = "https://raw.githubusercontent.com/couchbase/cbft/refs/heads/morpheus/docs/spec/manage/manage.yaml"
    outputDir = "${rootDir}/docs/modules/fts-rest-manage/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "cbft"
    gitUserId = "couchbase"
    additionalProperties = [
            specDir: "${rootDir}/docs/modules/fts-rest-manage/partials/",
            snippetDir: "${rootDir}/docs/modules/fts-rest-manage/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
}

tasks.openApiGenerate.dependsOn(getExamples)