= Couchbase Swagger Project

This proof-of-concept attempts to build inline examples into the AsciiDoc output using external example files referenced by the spec.

The process needs to handle single examples using the `example` key and multiple examples using the `examples` key, in both the request body and the responses.

* [x] The examples must be bundled into the spec.
      OpenAPI Generator does not do this.
      The Gradle build uses Redocly to bundle the examples.
* [x] OpenAPI continues to generate examples, even if inline examples are provided.
      The generated examples are stored in a different part of OpenAPI Generator's internal representation of the spec.
      Continue to set `skipExamples` to `true` so the generated examples are not included.
* [x] The inline examples are placed in the output in the same location where included example AsciiDoc file are placed by the OpenAPI Generator templates.
* [x] The OpenAPI Generator templates remove all line breaks and white space from the inline examples.
      The external example files should use the `jsonc` extension, so that line breaks are preserved in the output doc.
* [x] Multiple examples using the `examples` key should use the `externalValue` to reference the external example files.
      Otherwise, Redocly does not bundle the external example into the spec.
* [x] The templates cannot work with multiple examples, because Mustache has no way of parsing an object whose keys are not known.
      To fix this issue, try migrating the templates to Handlebars.
      This is beyond the scope of this proof-of-concept.