swagger: '2.0'
info:
  title: Couchbase Server API
  description: API for interacting with Couchbase Server
  version: "4.5.1"

host: localhost:1337/192.168.99.100:8092

schemes:
  - https
  - http

produces:
  - application/json

consumes:
  - application/json
  - formData

securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
    
paths:
  /{bucket_name}/_design/{ddoc_name}:
    get:
      summary: Gets design document definition.
      parameters:
        - $ref: "#/parameters/PathBucketName"
        - $ref: "#/parameters/PathDdocName"
      description: Returns the definition of the design document, including all javascript view definitions, as well as any reductions.
      responses:
        200:
          description: Success

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string

parameters:
  PathBucketName:
    name: bucket_name
    in: path
    type: string
    required: true
    description: name of a bucket
    
  PathDdocName:
    name: ddoc_name
    type: string
    in: path
    required: true
    
