plugins {
  id "com.github.node-gradle.node" version "7.1.0"
}

apply plugin: 'org.openapi.generator'

task bundleSpec(type: NpxTask) {
  command = '@redocly/cli'
  args = [
    'bundle',
    "${searchStatsSpec}",
    '-o', "attachments/${project.name}.bundle.yaml"]
}

openApiGenerate {
    generatorName = "asciidoc"
    inputSpec = file("attachments/${project.name}.bundle.yaml").getAbsolutePath().toString()
    outputDir = "${projectDir}/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "cbft"
    gitUserId = "couchbase"
    additionalProperties = [
            serviceDesc: "${project.name}.bundle.yaml",
            specDir: "${projectDir}/partials/",
            snippetDir: "${projectDir}/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "false",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
    engine = "handlebars"
}

tasks.openApiGenerate.dependsOn(bundleSpec)