openapi: 3.0.3
info:
  title: Couchbase Search Advanced API
  description: |-
    The Advanced Search REST APIs are provided by the Search service.
    These APIs enable you to manage and monitor advanced settings of your Search indexes.
  version: 1.0.0

servers:
  - url: '{scheme}://{host}:{port}'
    description: The URL scheme, host, and port are as follows.
    variables:
      scheme:
        default: http
        description: |-
          The URL scheme.
          Use `https` for secure access.
        enum:
          - http
          - https
      host:
        default: localhost
        description: The host name or IP address of a node running the Search service.
      port:
        default: "8094"
        description: |-
          The Search service REST port.
          Use `18094` for secure access.
        enum:
          - "8094"
          - "18094"

tags:
  - name: Definition
    x-displayName: Index Partition Definition
    description: Operations for index partition definition.
  - name: Query
    x-displayName: Index Partition Querying
    description: Operations for querying index partitions.
  - name: Quota
    x-displayName: FTS Memory Quota
    description: Operations for managing FTS memory quota.

paths:
  /api/pindex:
    get:
      operationId: getPartition
      summary: Get Index Partition Information
      description: Get information about an index partition.
      tags:
        - Definition
      responses:
        '200':
          description: A JSON object containing the index partition information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/indexPartition'
              example:
                $ref: '../../../docs/modules/fts-rest-advanced/examples/get-partition.json'
      security:
        - Read: []

  /api/pindex/{pindexName}:
    get:
      operationId: getPartitionName
      summary: Get Index Partition by Name
      description: Get information about a specific index partition by name.
      tags:
        - Definition
      parameters:
        - name: pindexName
          in: path
          required: true
          schema:
            type: string
          description: The name of the index partition.
      responses:
        '200':
          description: Success
      security:
        - Read: []

  /api/pindex/{pindexName}/count:
    get:
      operationId: getPartitionCount
      summary: Get Index Partition Document Count
      description: Get the document count of a specific index partition.
      tags:
        - Query
      parameters:
        - name: pindexName
          in: path
          required: true
          schema:
            type: string
          description: The name of the index partition.
      responses:
        '200':
          description: The Search Service returns a response that includes the status `ok`.
          content:
            application/json:
              schema:
                $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/DocumentCount'
      security:
        - Read: []

  /api/pindex/{pindexName}/query:
    post:
      operationId: queryPartition
      summary: Query Index Partition
      description: Execute a query against a specific index partition by name.
      tags:
        - Query
      parameters:
        - name: pindexName
          in: path
          required: true
          schema:
            type: string
          description: The name of the index partition.
      requestBody:
        required: true
        description: |-
          A JSON object to define the settings for your Search query.
          For more information about how to create a Search query JSON object, see [Search Request JSON Properties](../search/search-request-params.html).
        content:
          application/json:
            schema:
              $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/QueryRequest'
      responses:
        '200':
          description: |-
            The response object has a status section that must be checked for every request.
            Under nearly all circumstances, the query response will be HTTP 200 even though individual index shards (partitions) may encounter a timeout or return an error.
          content:
            application/json:
              schema:
                $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/QueryResponse'
      security:
        - Write: []

  /pools/default:
    post:
      operationId: setFtsMemoryQuota
      summary: Set FTS Memory Quota
      description: Sets the memory quota for the full text search (FTS) service.
      tags:
        - Quota
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                ftsMemoryQuota:
                  type: integer
                  description: The memory quota for the FTS service.
                  example: 512
                  x-has-example: true
      responses:
        '200':
          description: Memory quota set.
      security:
        - Manage: []

components:
  schemas:
    indexPartition:
      type: object
      title: Index Partitions
      properties:
        pindexes:
          $ref: '#/components/schemas/indexPartitionPIndex'
        status:
          description: The status of the request.
          type: string

    indexPartitionPIndex:
      type: object
      title: Index Partitions Wrapper
      description: An object containing information about one or more index partitions.
      additionalProperties:
        x-additionalPropertiesName: Partition Name
        $ref: '#/components/schemas/indexPartitionPIndexInner'

    indexPartitionPIndexInner:
      type: object
      title: Index Partition
      description: |-
        An object containing information about a single index partition.
        The name of the property is the name of the index partition.
      properties:
        indexName:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonIndexName'
        indexParams:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonIndexParams'
        indexType:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonIndexType'
        indexUUID:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonIndexUUID'
        name:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonPIndexName'
        sourceName:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonSourceName'
        sourceParams:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonSourceParams'
        sourcePartitions:
          type: string
        sourceType:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonSourceType'
        sourceUUID:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonSourceUUID'
        uuid:
          $ref: '../../search-index/swagger/search-index.yaml#/components/schemas/CommonPIndexUUID'

  securitySchemes:
    Manage:
      type: http
      scheme: basic
      description: |-
        You must have the **Search Admin** role, with FTS Manage permissions on the required bucket.

    Read:
      type: http
      scheme: basic
      description: |-
        You must have the **Search Reader** or **Search Admin** role, with FTS Read permissions on the required bucket.

    Write:
      type: http
      scheme: basic
      description: |-
        You must have the **Search Admin** role, with FTS Write permissions on the required bucket.
