apply plugin: 'org.openapi.generator'

tasks.register('getExamples') {
  doLast {
    ant.property(name: "srcUrl",
                value: "https://raw.githubusercontent.com/couchbase/query/refs/heads/trinity/docs/spec/settings/examples")
    ant.echo("Fetching from ${ant.srcUrl}")
      ant.url(url: "${ant.srcUrl}/query-settings-get-access.jsonc")
      ant.url(url: "${ant.srcUrl}/query-settings-get-access.sh")
      ant.url(url: "${ant.srcUrl}/query-settings-get-settings.jsonc")
      ant.url(url: "${ant.srcUrl}/query-settings-get-settings.sh")
      ant.url(url: "${ant.srcUrl}/query-settings-post-access.jsonc")
      ant.url(url: "${ant.srcUrl}/query-settings-post-access.sh")
      ant.url(url: "${ant.srcUrl}/query-settings-post-settings.jsonc")
      ant.url(url: "${ant.srcUrl}/query-settings-post-settings.sh")
      ant.url(url: "${ant.srcUrl}/query-settings-post-snippet.jsonc")
    }
  }
}

openApiGenerate {
    generatorName = "asciidoc"
    remoteInputSpec = "https://raw.githubusercontent.com/couchbase/query/refs/heads/trinity/docs/spec/settings/settings.yaml"
    outputDir = "${rootDir}/docs/modules/n1ql-rest-settings/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "query"
    gitUserId = "couchbase"
    additionalProperties = [
            specDir: "${rootDir}/docs/modules/n1ql-rest-settings/partials/",
            snippetDir: "${rootDir}/docs/modules/n1ql-rest-settings/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
}

tasks.openApiGenerate.dependsOn(getExamples)