apply plugin: 'org.openapi.generator'

tasks.register('getExamples') {
  doLast {
    ant.property(name: "srcUrl",
                value: "https://raw.githubusercontent.com/couchbase/cbft/refs/heads/trinity/docs/spec/index/examples")
    ant.echo("Fetching from ${ant.srcUrl}")
    ant.get(dest: "examples", ignoreerrors: "true") {
      ant.url(url: "${ant.srcUrl}/d-api-index-name-200.json")
      ant.url(url: "${ant.srcUrl}/d-api-index-name-default.json")
      ant.url(url: "${ant.srcUrl}/d-api-scoped-index-name-200.json")
      ant.url(url: "${ant.srcUrl}/d-api-scoped-index-name-default.json")
      ant.url(url: "${ant.srcUrl}/fts-sample-index-def-response.json")
      ant.url(url: "${ant.srcUrl}/fts-sample-success-response-vector-search.json")
      ant.url(url: "${ant.srcUrl}/fts-sample-success-response.json")
      ant.url(url: "${ant.srcUrl}/g-api-index-name-count.json")
      ant.url(url: "${ant.srcUrl}/g-api-index-name.json")
      ant.url(url: "${ant.srcUrl}/g-api-index.json")
      ant.url(url: "${ant.srcUrl}/g-api-scoped-indexes.json")
      ant.url(url: "${ant.srcUrl}/g-api-scoped-status.json")
      ant.url(url: "${ant.srcUrl}/g-api-stats-index-name-analyzeDoc-200.json")
      ant.url(url: "${ant.srcUrl}/g-api-stats-index-name-analyzeDoc-body.json")
      ant.url(url: "${ant.srcUrl}/g-api-stats-index-name.json")
      ant.url(url: "${ant.srcUrl}/g-api-stats.json")
      ant.url(url: "${ant.srcUrl}/p-api-index-name-200.json")
      ant.url(url: "${ant.srcUrl}/p-api-index-name-default.json")
      ant.url(url: "${ant.srcUrl}/p-api-index-name-query-hybrid.json")
      ant.url(url: "${ant.srcUrl}/p-api-index-name-query-options.json")
      ant.url(url: "${ant.srcUrl}/p-api-index-name-query-regular.json")
      ant.url(url: "${ant.srcUrl}/p-api-pindex-lookup-200.json")
      ant.url(url: "${ant.srcUrl}/p-api-pindex-lookup-body.json")
      ant.url(url: "${ant.srcUrl}/p-api-scoped-index-name-200.json")
      ant.url(url: "${ant.srcUrl}/p-api-scoped-index-name-default.json")
      ant.url(url: "${ant.srcUrl}/p-api-scoped-query-default.json")
      ant.url(url: "${ant.srcUrl}/response-200.json")
    }
  }
}

openApiGenerate {
    generatorName = "asciidoc"
    remoteInputSpec = "https://raw.githubusercontent.com/couchbase/cbft/refs/heads/trinity/docs/spec/index/index.yaml"
    outputDir = "${rootDir}/docs/modules/fts-rest-indexing/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "cbft"
    gitUserId = "couchbase"
    additionalProperties = [
            specDir: "${rootDir}/docs/modules/fts-rest-indexing/partials/",
            snippetDir: "${rootDir}/docs/modules/fts-rest-indexing/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
}

tasks.openApiGenerate.dependsOn(getExamples)