apply plugin: 'org.openapi.generator'

tasks.register('getExamples') {
  doLast {
    ant.property(name: "srcUrl",
                value: "https://raw.githubusercontent.com/couchbase/query/refs/heads/trinity/docs/spec/service/examples")
    ant.echo("Fetching from ${ant.srcUrl}")
    ant.get(dest: "examples") {
      ant.url(url: "${ant.srcUrl}/exformdata.sh")
      ant.url(url: "${ant.srcUrl}/exn1qlerror.json")
      ant.url(url: "${ant.srcUrl}/exnamed.json")
      ant.url(url: "${ant.srcUrl}/exnamed.sh")
      ant.url(url: "${ant.srcUrl}/exnotfound.json")
      ant.url(url: "${ant.srcUrl}/exnumbered.json")
      ant.url(url: "${ant.srcUrl}/exnumbered.sh")
      ant.url(url: "${ant.srcUrl}/expositional.json")
      ant.url(url: "${ant.srcUrl}/expositional.sh")
      ant.url(url: "${ant.srcUrl}/exreadonly.sh")
      ant.url(url: "${ant.srcUrl}/exrequesterror.json")
      ant.url(url: "${ant.srcUrl}/exserviceerror.json")
      ant.url(url: "${ant.srcUrl}/exsuccessful.json")
      ant.url(url: "${ant.srcUrl}/exsuccessful.sh")
      ant.url(url: "${ant.srcUrl}/exwildcard.json")
      ant.url(url: "${ant.srcUrl}/exwildcard.sh")
    }
  }
}

openApiGenerate {
    generatorName = "asciidoc"
    remoteInputSpec = "https://raw.githubusercontent.com/couchbase/query/refs/heads/trinity/docs/spec/service/service.yaml"
    outputDir = "${rootDir}/docs/modules/n1ql-rest-query/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "query"
    gitUserId = "couchbase"
    additionalProperties = [
            specDir: "${rootDir}/docs/modules/n1ql-rest-query/partials/",
            snippetDir: "${rootDir}/docs/modules/n1ql-rest-query/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
}

tasks.openApiGenerate.dependsOn(getExamples)