plugins {
    id "com.github.node-gradle.node" version "7.1.0"
    id("io.datapith.jayOverlay").version("0.1.11")
}

apply plugin: 'org.openapi.generator'

task bundleSpec(type: NpxTask) {
  command = '@redocly/cli'
  args = [
    'bundle',
    'https://raw.githubusercontent.com/couchbase/query/refs/heads/morpheus/docs/spec/service/service.yaml',
    '-o', "build/${project.name}.bundle.yaml"]
}

jayOverlay {
    targetFile.set("${projectDir}/build/${project.name}.bundle.yaml")
    overlayFile.set("${projectDir}/attachments/_overlay.json")
    outputDir.set("${projectDir}/attachments")
}

tasks.applyOverlay.doLast {
    ant.move(file:   "${projectDir}/attachments/${project.name}.bundle.yaml",
             tofile: "${projectDir}/attachments/_${project.name}.overlaid.yaml",
             overwrite: "true")
}

openApiGenerate {
    generatorName = "asciidoc"
    inputSpec = file("attachments/_${project.name}.overlaid.yaml").getAbsolutePath().toString()
    outputDir = "${projectDir}/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "query"
    gitUserId = "couchbase"
    additionalProperties = [
            serviceDesc: "_${project.name}.overlaid.yaml",
            specDir: "${projectDir}/partials/",
            snippetDir: "${projectDir}/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
    engine = "handlebars"
}

tasks.applyOverlay.dependsOn(bundleSpec)
tasks.openApiGenerate.dependsOn(applyOverlay)
