apply plugin: 'org.openapi.generator'

openApiGenerate {
    generatorName = "asciidoc"
    inputSpec = file("attachments/${name}.yaml").getAbsolutePath().toString()
    outputDir = "${projectDir}/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "cb-swagger"
    gitUserId = "couchbaselabs"
    additionalProperties = [
            serviceDesc: "${name}.yaml",
            specDir: "${projectDir}/partials/",
            snippetDir: "${projectDir}/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
    engine = "handlebars"
}
