apply plugin: 'org.openapi.generator'

tasks.register('getExamples') {
  doLast {
    ant.property(name: "srcUrl",
                value: "https://raw.githubusercontent.com/couchbase/query/refs/heads/master/docs/spec/functions/examples")
    ant.echo("Fetching from ${ant.srcUrl}")
    ant.get(dest: "examples", ignoreerrors: "true") {
      ant.url(url: "${ant.srcUrl}/delete_library_global.sh")
      ant.url(url: "${ant.srcUrl}/delete_library_scope.sh")
      ant.url(url: "${ant.srcUrl}/get_collection_all.sh")
      ant.url(url: "${ant.srcUrl}/get_collection_all.json")
      ant.url(url: "${ant.srcUrl}/get_collection_scope.sh")
      ant.url(url: "${ant.srcUrl}/get_collection_scope.json")
      ant.url(url: "${ant.srcUrl}/get_library_global.sh")
      ant.url(url: "${ant.srcUrl}/get_library_global.json")
      ant.url(url: "${ant.srcUrl}/get_library_scope.sh")
      ant.url(url: "${ant.srcUrl}/get_library_scope.json")
      ant.url(url: "${ant.srcUrl}/post_library_global_add.sh")
      ant.url(url: "${ant.srcUrl}/post_library_global_create.sh")
      ant.url(url: "${ant.srcUrl}/post_library_global_delete.sh")
      ant.url(url: "${ant.srcUrl}/post_library_global_edit.sh")
      ant.url(url: "${ant.srcUrl}/post_library_scope.sh")
    }
  }
}

openApiGenerate {
    generatorName = "asciidoc"
    remoteInputSpec = "https://raw.githubusercontent.com/couchbase/query/refs/heads/master/docs/spec/functions/functions.yaml"
    outputDir = "${rootDir}/docs/modules/n1ql-rest-functions/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "query"
    gitUserId = "couchbase"
    additionalProperties = [
            specDir: "${rootDir}/docs/modules/n1ql-rest-functions/partials/",
            snippetDir: "${rootDir}/docs/modules/n1ql-rest-functions/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
}

tasks.openApiGenerate.dependsOn(getExamples)