apply plugin: 'org.openapi.generator'

openApiGenerate {
    generatorName = "asciidoc"
    remoteInputSpec = "https://raw.githubusercontent.com/couchbase/query/refs/heads/morpheus/docs/spec/functions/functions.yaml"
    outputDir = "${rootDir}/docs/modules/n1ql-rest-functions/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "query"
    gitUserId = "couchbase"
    additionalProperties = [
            specDir: "${rootDir}/docs/modules/n1ql-rest-functions/partials/",
            snippetDir: "${rootDir}/docs/modules/n1ql-rest-functions/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
}