= Consistency and Timeouts

A query can specify a timeout value, a consistency requirement, or both.
This section explains how this affects the query behavior and how to handle the resulting query return values.

* Logical first phase consistency wait -- if timeout in this period, get 416 error with message saying request could not be satisfied.

* If consistency wait times out with 416, return value to client will indicate the sequence number range processed so the client will have an idea how far the processing got and has the option of retrying more intelligently.

* In phase 2, you have the normal pindex timeout.
This will start whenever the first phase completes.
At this point, request will return 200 HTTP response code unless there is an internal server error.

* Client must check response status, which will return any errors or timeouts for each pindex.
If the response includes the number of errors, and the client can determine whether they need the complete results or can continue as long as enough pindexes return to give a reasonable user experience.
Note that the query return status will be 200 even if all pindexes return errors so it's critical to check the response status and code accordingly.

* If client sets timeout very low, e.g. 1ms, you may receive a 200 error with all timeouts instead of a consistency wait timeout.
