apply plugin: 'org.openapi.generator'

tasks.register('getExamples') {
  doLast {
    ant.property(name: "srcUrl",
                value: "https://raw.githubusercontent.com/couchbase/cbft/refs/heads/trinity/docs/spec/advanced/examples")
    ant.echo("Fetching from ${ant.srcUrl}")
    ant.get(dest: "examples") {
      ant.url(url: "${ant.srcUrl}/get-partition.json")
    }
  }
}

openApiGenerate {
    generatorName = "asciidoc"
    remoteInputSpec = "https://raw.githubusercontent.com/couchbase/cbft/refs/heads/trinity/docs/spec/advanced/advanced.yaml"
    outputDir = "${rootDir}/docs/modules/fts-rest-advanced/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "cbft"
    gitUserId = "couchbase"
    additionalProperties = [
            specDir: "${rootDir}/docs/modules/fts-rest-advanced/partials/",
            snippetDir: "${rootDir}/docs/modules/fts-rest-advanced/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
}

tasks.openApiGenerate.dependsOn(getExamples)