plugins {
  id "com.github.node-gradle.node" version "7.1.0"
}

apply plugin: 'org.openapi.generator'

task bundleSpec(type: NpxTask) {
  command = '@redocly/cli'
  args = [
    'bundle',
    'https://raw.githubusercontent.com/couchbase/query/refs/heads/trinity/docs/spec/admin/admin.yaml',
    '-o', 'attachments/${name}.bundle.yaml']
}

openApiGenerate {
    generatorName = "asciidoc"
    inputSpec = file("attachments/${name}.bundle.yaml").getAbsolutePath().toString()
    outputDir = "${rootDir}/docs/modules/n1ql-rest-admin/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "query"
    gitUserId = "couchbase"
    additionalProperties = [
            projectName: "${name}",
            specDir: "${rootDir}/docs/modules/n1ql-rest-admin/partials/",
            snippetDir: "${rootDir}/docs/modules/n1ql-rest-admin/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
    engine = "handlebars"
}

tasks.openApiGenerate.dependsOn(bundleSpec)