swagger: '2.0'
info:
  title: Analytics Service REST API
  version: '8.0'
  description: |
    The Analytics Service REST API is provided by the Analytics service.
    This API enables you to run Analytics queries and set request-level parameters.

host: localhost:8095

schemes:
  - http

produces:
  - application/json

consumes:
  - application/json
  - application/x-www-form-urlencoded

paths:
  /analytics/service:
    post:
      operationId: post_service
      summary: Query Service
      description: >
        Enables you to execute a SQL\+\+ for Analytics statement.
        This method allows you to run queries and modifying statements, and specify query parameters.
      parameters:
        - in: body
          name: Parameters
          required: true
          description: An object specifying one or more query parameters.
          schema:
            $ref: "#/definitions/Parameters"
      security:
        - Analytics Manage / Analytics Select: []
      responses:
        "200":
          $ref: '#/responses/OK'
        "400":
          $ref: '#/responses/BadRequest'
        "401":
          $ref: '#/responses/Unauthorized'
    get:
      operationId: get_service
      summary: Read-Only Query Service
      description: >
        Enables you to execute a SQL\+\+ for Analytics statement.
        This method only allows you to run queries and specify query parameters.
        It does not allow you to run modifying statements.


        This is intended for situations where use of the `POST` method is restricted.
      parameters:
        - $ref: "#/parameters/CommonStatement"
        - $ref: "#/parameters/CommonClientContextId"
        - $ref: "#/parameters/CommonFormat"
        - $ref: "#/parameters/CommonPretty"
        - $ref: "#/parameters/CommonQueryContext"
        - $ref: "#/parameters/CommonReadonly"
        - $ref: "#/parameters/CommonScanConsistency"
        - $ref: "#/parameters/CommonScanWait"
        - $ref: "#/parameters/CommonTimeout"
        - $ref: "#/parameters/CommonArgs"
        - $ref: "#/parameters/CommonIdentifier"
        - $ref: "#/parameters/AnalyticsPlanFormat"
        - $ref: "#/parameters/AnalyticsLogicalPlan"
        - $ref: "#/parameters/AnalyticsOptimizedLogicalPlan"
        - $ref: "#/parameters/AnalyticsExpressionTree"
        - $ref: "#/parameters/AnalyticsRewrittenExpressionTree"
        - $ref: "#/parameters/AnalyticsJob"
        - $ref: "#/parameters/AnalyticsMaxWarnings"

      security:
        - Analytics Manage / Analytics Select: []
      responses:
        "200":
          $ref: '#/responses/OK'
        "400":
          $ref: '#/responses/BadRequest'
        "401":
          $ref: '#/responses/Unauthorized'

  /query/service:
    post:
      operationId: post_query
      summary: Query Service (Alternative)
      description: An alternative endpoint for the [Query Service](#post_service), provided for tools compatibility.
      parameters:
        - in: body
          name: Parameters
          required: true
          description: An object specifying one or more query parameters.
          schema:
            $ref: "#/definitions/Parameters"
      responses:
        "200":
          $ref: '#/responses/OK'
        "400":
          $ref: '#/responses/BadRequest'
        "401":
          $ref: '#/responses/Unauthorized'
    get:
      operationId: get_query
      summary: Read-Only Query Service (Alternative)
      description: An alternative endpoint for the [Read-Only Query Service](#get_service), provided for tools compatibility.
      responses:
        "200":
          $ref: '#/responses/OK'
        "400":
          $ref: '#/responses/BadRequest'
        "401":
          $ref: '#/responses/Unauthorized'

definitions:

  # For the REST API reference
  Parameters:
    title: Query Parameters
    allOf:
      - $ref: "#/definitions/ParametersCommon"
      - $ref: "#/definitions/ParametersLocal"

  # For the Query Parameters page
  # Use YAML anchors for properties which are also available as query parameters
  ParametersCommon:
    title: Common Parameters
    type: object
    required:
      - statement
    properties:
      statement: &statement
        type: string
        description: Specifies at least one valid SQL\+\+ for Analytics statement to run.
      client_context_id: &client_context_id
        type: string
        description: >
          An identifier passed by the client that is returned verbatim in the query response.
          Useful for matching a particular query to a specific caller.
      format: &format
        type: string
        x-has-default: true
        default: JSON
        description: |
          Desired format for the query results.
          
          Note that the only possible format is `JSON`.
        enum:
          - JSON
      pretty: &pretty
        type: boolean
        x-has-default: true
        default: false
        description: If `true`, the result is indented.
      query_context: &query_context
        type: string
        description: >
          A scope for the statement.
          The value of this parameter must start with `default:`, followed by an Analytics scope name.
          The `default:` prefix is a dummy and is ignored when resolving an Analytics collection name or synonym name.
        x-has-default: true
        default: default:Default
      readonly: &readonly
        type: boolean
        x-has-default: true
        default: false
        description: If `true`, then DDL statements are not allowed.
      scan_consistency: &scan_consistency
        type: string
        x-has-default: true
        default: not_bounded
        description: >
          The consistency guarantee constraint for index scanning.
          If `not_bounded`, the query is executed immediately.
          If `request_plus`, the required datasets are updated with data available from the Data service at the time of the request before the query is executed.
        enum:
          - not_bounded
          - request_plus
      scan_wait: &scan_wait
        type: string
        x-has-default: false
        default: ""
        description: >
          The maximum time to wait for datasets to be updated before the query is executed.
          The format includes an amount and a unit: `ns`, `us`, `ms`, `s`, `m`, or `h`.
          The default is `""` (no timeout).
      timeout: &timeout
        type: string
        x-has-default: false
        default: ""
        description: >
          Maximum time to spend on the request before timing out.
          The format includes an amount and a unit: `ns`, `us`, `ms`, `s`, `m`, or `h`.
          The default is `""` (no timeout).
      args: &args
        type: array
        description: An array of positional parameter values.
        items: {}
    additionalProperties: &identifier
        type: string
        description: A named parameter value.

  # For the Query Parameters page
  # Use YAML anchors for properties which are also available as query parameters
  ParametersLocal:
    title: Analytics Parameters
    type: object
    properties:
      plan-format: &plan_format
        type: string
        description: The plan format.
        x-has-default: true
        default: JSON
        enum:
          - JSON
          - STRING
      logical-plan: &logical_plan
        type: boolean
        description: If `true`, the logical plan is included in the query response.
        x-has-default: true
        default: false
      optimized-logical-plan: &organized_logical_plan
        type: boolean
        description: If `true`, the optimized logical plan is included in the query response.
        x-has-default: true
        default: true
      expression-tree: &expression_tree
        type: boolean
        description: If `true`, the expression tree is included in the query response.
        x-has-default: true
        default: false
      rewritten-expression-tree: &rewritten_expression_tree
        type: boolean
        description: If `true`, the rewritten expression tree is included in the query response.
        x-has-default: true
        default: false
      job: &job
        type: boolean
        description: If `true`, the job details are included in the query response.
        x-has-default: true
        default: false
      max-warnings: &max_warnings
        type: integer
        format: int32
        description: An integer specifying the maximum number of warning messages to be included in the query response.
        x-has-default: true
        default: 0

  # For the REST API reference
  # The odd definition names ensure that the schemas appear in a logical order
  Responses:
    title: Query Responses
    allOf:
      - $ref: "#/definitions/ResponsesCommon"
      - $ref: "#/definitions/ResponsesLocal"

  # For the Query Responses page
  ResponsesCommon:
        title: Common Responses
        type: object
        properties:
          requestID:
            type: string
            format: UUID
            description: A unique identifier for the response.
          clientContextID:
            type: string
            description: |-
              The client context ID of the request, if one was supplied —
              refer to `client_context_id` in [Query Parameters][1].

              [1]: #Parameters
            x-desc-refs: |-
              [1]: query-params.html
          signature:
            type: object
            description: >
              The schema of the results.
              Present only when the query completes successfully.
          results:
            type: array
            description: >
              An array of all the objects returned by the query.
              An object can be any JSON value.
            items: {}
          status:
            type: string
            description: The status of the request.
            enum:
              - success
              - running
              - failed
              - timeout
              - fatal
          errors:
            type: array
            description: >
              An array of error objects.
              Present only if 1 or more errors are returned during processing of the request.
              Each error is represented by an object in this list.
            items:
              $ref: "#/definitions/ResponsesCommonErrors"
          warnings:
            type: array
            description: |-
              An array of warning objects.
              Present only if 1 or more warnings are returned during processing of the request.
              Each warning is represented by an object in this list.

              Note that you can specify the maximum number of warning messages to be returned in the query response —
              refer to `max-warnings` in [Query Parameters][1].
              By default, no warnings are returned, even if warnings have occurred during processing.

              [1]: #Parameters
            x-desc-refs: |-
              [1]: query-params.html
            items:
              $ref: "#/definitions/ResponsesCommonWarnings"
          metrics:
            $ref: "#/definitions/ResponsesCommonYardsticks"

  # For the Query Responses page
  ResponsesLocal:
        title: Analytics Responses
        type: object
        properties:
          plans:
            $ref: "#/definitions/ResponsesLocalPlans"
          metrics:
            $ref: "#/definitions/ResponsesLocalYardsticks"

  # For the Query Responses page
  ResponsesCommonErrors:
    title: Errors
    type: object
    properties:
      code:
        type: integer
        description: A number that identifies the error.
      msg:
        type: string
        description: >
          A message describing the error in detail.
          Refer to [Error Codes](/server/7.6/analytics/error-codes.html).

  # For the Query Responses page
  ResponsesCommonWarnings:
    title: Warnings
    type: object
    properties:
      code:
        type: integer
        description: A number that identifies the warning.
      msg:
        type: string
        description: A message describing the warning in detail.

  # For the Query Responses page
  ResponsesLocalPlans:
    title: Plans
    type: object
    description: An object containing the query plans, if requested.
    properties:
      logicalPlan:
        type: object
        description: The logical plan.
      optimizedLogicalPlan:
        type: object
        description: The optimized logical plan.
      rewrittenExpressionTree:
        type: string
        description: The rewritten expression tree.
      expressionTree:
        type: string
        description: The expression tree.
      job:
        type: object
        description: The job details.

  # For the Query Responses page
  ResponsesCommonYardsticks:
    title: Common Metrics
    type: object
    description: An object containing metrics about the request.
    properties:
      elapsedTime:
        type: string
        description: >
          The total time taken for the request,
          that is the time from when the request was received until the results were returned.
      executionTime:
        type: string
        description: >
          The time taken for the execution of the request,
          that is the time from when query execution started until the results were returned.
      resultCount:
        type: integer
        format: unsigned
        description: The total number of objects in the results.
      resultSize:
        type: integer
        format: unsigned
        description: The total number of bytes in the results.
      errorCount:
        type: integer
        format: unsigned
        description: The number of errors that occurred during the request.
      warningCount:
        type: integer
        format: unsigned
        description: The number of warnings that occurred during the request.

  # For the Query Responses page
  ResponsesLocalYardsticks:
    title: Analytics Metrics
    type: object
    description: An object containing metrics about the request.
    properties:
      processedObjects:
        type: integer
        format: int64
        description: Number of processed tuples during query execution.

parameters:
  CommonStatement:
    <<: *statement
    name: statement
    in: query
    required: true

  CommonClientContextId:
    <<: *client_context_id
    name: client_context_id
    in: query
    required: false

  CommonFormat:
    <<: *format
    name: format
    in: query
    required: false

  CommonPretty:
    <<: *pretty
    name: pretty
    in: query
    required: false

  CommonQueryContext:
    <<: *query_context
    name: query_context
    in: query
    required: false

  CommonReadonly:
    <<: *readonly
    name: readonly
    in: query
    required: false

  CommonScanConsistency:
    <<: *scan_consistency
    name: scan_consistency
    in: query
    required: false

  CommonScanWait:
    <<: *scan_wait
    name: scan_wait
    in: query
    required: false

  CommonTimeout:
    <<: *timeout
    name: timeout
    in: query
    required: false

  CommonArgs:
    <<: *args
    name: args
    in: query
    required: false
    items:
      type: string
      format: URL-encoded

  CommonIdentifier:
    <<: *identifier
    name: $_identifier_
    in: query
    required: false

  AnalyticsPlanFormat:
    <<: *plan_format
    name: plan-format
    in: query
    required: false

  AnalyticsLogicalPlan:
    <<: *logical_plan
    name: logical-plan
    in: query
    required: false

  AnalyticsOptimizedLogicalPlan:
    <<: *organized_logical_plan
    name: organized-logical-plan
    in: query
    required: false

  AnalyticsExpressionTree:
    <<: *expression_tree
    name: expression-tree
    in: query
    required: false

  AnalyticsRewrittenExpressionTree:
    <<: *rewritten_expression_tree
    name: rewritten-expression-tree
    in: query
    required: false

  AnalyticsJob:
    <<: *job
    name: job
    in: query
    required: false

  AnalyticsMaxWarnings:
    <<: *max_warnings
    name: max-warnings
    in: query
    required: false

responses:
  OK:
    description: The operation was successful.
    schema:
      $ref: "#/definitions/Responses"

  BadRequest:
    description: >
      Bad request.
      A parameter has an incorrect value.
    schema:
      $ref: "#/definitions/Responses"

  Unauthorized:
    description: >
      Unauthorized.
      The user name or password may be incorrect.
    schema:
      $ref: "#/definitions/Responses"

securityDefinitions:
  Analytics Manage / Analytics Select:
    type: basic
    description: |-
      Users must have one of the following RBAC roles:

      * Full Admin
      * Cluster Admin
      * Analytics Manager
      * Analytics Reader
      * Analytics Select
      * Analytics Admin