plugins {
  id "com.github.node-gradle.node" version "7.1.0"
}

apply plugin: 'org.openapi.generator'

task bundleSpec(type: NpxTask) {
  command = '@redocly/cli'
  args = [
    'bundle',
    'https://raw.githubusercontent.com/couchbase/cbft/refs/heads/trinity/docs/spec/query/query.yaml',
    '-o', 'attachments/${name}.bundle.yaml']
}

openApiGenerate {
    generatorName = "asciidoc"
    inputSpec = file("attachments/${name}.bundle.yaml").getAbsolutePath().toString()
    outputDir = "${rootDir}/docs/modules/fts-rest-query/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "cbft"
    gitUserId = "couchbase"
    additionalProperties = [
            serviceDesc: "${name}.bundle.yaml",
            specDir: "${rootDir}/docs/modules/fts-rest-query/partials/",
            snippetDir: "${rootDir}/docs/modules/fts-rest-query/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
    engine = "handlebars"
}

tasks.openApiGenerate.dependsOn(bundleSpec)