plugins {
    id("io.datapith.jayOverlay").version("0.1.11")
}

jayOverlay {
    targetFile.set("${projectDir}/build/${name}.bundle.yaml")
    overlayFile.set("${projectDir}/attachments/_overlay.json")
    outputDir.set("${projectDir}/attachments")
}

apply plugin: 'org.openapi.generator'

task bundleSpec(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "openapi-yaml"
    inputSpec = file("attachments/_${name}.yaml").getAbsolutePath().toString()
    outputDir = "${projectDir}/build"
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    additionalProperties = [
            outputFile: "${name}.bundle.yaml",
    ]
    generateAliasAsModel = true
}

openApiGenerate {
    generatorName = "asciidoc"
    inputSpec = file("attachments/${name}.overlaid.yaml").getAbsolutePath().toString()
    outputDir = "${projectDir}/pages"
    templateDir = "${rootDir}/templates"
    gitRepoId = "cb-swagger"
    gitUserId = "couchbaselabs"
    additionalProperties = [
            serviceDesc: "${name}.overlaid.yaml",
            specDir: "${projectDir}/partials/",
            snippetDir: "${projectDir}/partials/paths/",
            headerAttributes: "true",
            useIntroduction: "true",
            useTableTitles: "true",
            skipExamples: "true",
            legacyDiscriminatorBehavior: "true"
    ]
    globalProperties = [
            generateAliasAsModel: "true"
    ]
    generateAliasAsModel = true
    engine = "handlebars"
    modelNameMappings = [
            handler_schema: "Function Definition",
            function_scope_schema: "Function Scope",
            settings_schema: "Function Settings",
            depcfg_schema: "Deployment Config",
            depcfg_schema_buckets_inner: "Deployment Keyspace",
            depcfg_schema_constants_inner: "Deployment Constants",
            depcfg_schema_curl_inner: "Deployment URL"
    ]
}

tasks.applyOverlay.dependsOn(bundleSpec)
tasks.openApiGenerate.dependsOn(applyOverlay)
