swagger: '2.0'
info:
  title: Index Settings REST API
  version: '1.0'
  description: |
    The Index Settings REST API is provided by the index service.
    This API enables you to retrieve or set index service settings.

    The API schemes and host URLs are as follows:{blank}

    * `+http://node:9102/+`
    * `+https://node:19102/+` (for secure access)

    where [.var]`node` is the host name or IP address of a computer running the index service.

produces:
  - application/json

paths:
  /settings:
    get:
      operationId: get_settings
      summary: Retrieve Index Settings
      description: Returns index service settings.
      security:
        - Default: []
      responses:
        200:
          description: An object giving index service settings.
          schema:
            $ref: "#/definitions/Settings"
    post:
      operationId: post_settings
      summary: Update Index Settings
      description: Updates index service settings.
      security:
        - Default: []
      parameters:
        - $ref: "#/parameters/BodySettings"
      responses:
        200:
          description: An object giving index service settings, including the latest changes.
          schema:
            $ref: "#/definitions/Settings"

parameters:
  BodySettings:
    in: body
    name: Settings
    required: true
    description: An object specifying index service settings.
    schema:
      $ref: "#/definitions/Settings"

definitions:
  Settings:
    type: object
    properties:
      indexer.settings.allow_large_keys:
        type: boolean
        default: true
        description: |
          Whether the size of index keys is unlimited.

          * If true, index keys may have unlimited size.
          * If false, the maximum size for index keys and array index keys is specified by `indexer.{wbr}settings.{wbr}max_seckey_size` and `indexer.{wbr}settings.{wbr}max_array_seckey_size`.

          In Couchbase Server 6.5 and later, the index service does not need to restart when you update this setting.
      indexer.settings.bufferPoolBlockSize:
        type: integer
        format: int32
        default: 16384
        description: |
          FIXME: Buffer pool block size.
      indexer.settings.build.batch_size:
        type: integer
        format: int32
        default: 5
        description: |
          FIXME: Build batch size.
      indexer.settings.compaction.abort_exceed_interval:
        type: boolean
        default: false
        description: |
          FIXME: Whether to abort index compaction if it is still running after the end of the index compaction interval.
      indexer.settings.compaction.check_period:
        type: integer
        format: int32
        default: 30
        description: An interval, specifying how frequently the index service checks whether the compaction threshold has been reached (seconds).
      indexer.settings.compaction.compaction_mode:
        type: string
        default: circular
        description: The compaction mode for indexes.
        enum:
          - standard
          - circular
      indexer.settings.compaction.days_of_week:
        type: string
        example: Saturday,Sunday
        default: Sunday,{wbr}Monday,{wbr}Tuesday,{wbr}Wednesday,{wbr}Thursday,{wbr}Friday,{wbr}Saturday
        description: |
          The days of the week on which circular compaction is to run, if specified.
          Individual values must be day-names, each specified with an initial capital, and otherwise lower-case.
          Multiple values must be separated by a single comma, with no spaces.
      indexer.settings.compaction.interval:
        type: string
        example: 01:00,05:59
        default: 00:00,00:00
        description: |
          A string in the form *_fromHour:fromMinute,{wbr}toHour:toMinute_*, specifying the interval during which index compaction can run.
          
          fromHour::
            An integer between 0 and 23 inclusive, specifying the starting hour of the interval.
          fromMinute::
            An integer between 0 and 59 inclusive, specifying the starting minute of the interval, within the specified starting hour.
          toHour::
            An integer between 0 and 23 inclusive, specifying the concluding hour of the interval.
          toMinute::
            An integer between 0 and 59 inclusive, specifying the concluding minute of the interval, within the specified concluding hour.
          
          The default value means any time.
      indexer.settings.compaction.min_frag:
        type: integer
        format: int32
        default: 30
        minimum: 5
        description: The minimum fragmentation threshold to trigger compaction (percentage).
      indexer.settings.compaction.min_size:
        type: integer
        format: int32
        default: 524288000
        description: Compaction minimum file size.
      indexer.settings.compaction.plasma.manual:
        type: boolean
        default: false
        description: |
          FIXME: For standard indexes using Plasma, whether compaction should be triggered manually.
      indexer.settings.compaction.plasma.optional.decrement:
        type: integer
        format: int32
        default: 5
        description: |
          FIXME: For standard indexes using Plasma, the optional decrement.
      indexer.settings.compaction.plasma.optional.min_frag:
        type: integer
        format: int32
        default: 20
        description: |
          FIXME: For standard indexes using Plasma, the minimum fragmentation threshold to trigger compaction (percentage).
      indexer.settings.compaction.plasma.optional.quota:
        type: integer
        format: int32
        default: 25
        description: |
          FIXME: For standard indexes using Plasma, the optional quota.
      indexer.settings.corrupt_index_num_backups:
        type: integer
        format: int32
        default: 1
        description: |
          FIXME: Corrupt index number of backups.
      indexer.settings.cpuProfFname:
        type: string
        description: |
          FIXME: The name of the file where local CPU usage profiling information is captured.
      indexer.settings.cpuProfile:
        type: boolean
        default: false
        description: |
          FIXME: Whether the index service should capture local CPU usage profiling information.
      indexer.settings.enable_corrupt_index_backup:
        type: boolean
        default: false
        description: |
          FIXME: Whether corrupt index backup is enabled.
      indexer.settings.fast_flush_mode:
        type: boolean
        default: true
        description: |
          FIXME: Whether fast flush mode is enabled.
      indexer.settings.gc_percent:
        type: integer
        format: int32
        default: 100
        description: |
          FIXME: Garbage collection percentage.
      indexer.settings.inmemory_snapshot.fdb.interval:
        type: integer
        format: int32
        default: 200
        minimum: 1
        exclusiveMinimum: true
        description: |
          For standard indexes using ForestDB, the in-memory snapshotting interval (ms).
          This determines the earliest possibility of a scan seeing a given KV mutation.
      indexer.settings.inmemory_snapshot.interval:
        type: integer
        format: int32
        default: 200
        minimum: 1
        exclusiveMinimum: true
        description: |
          The in-memory snapshotting interval (ms).
          This determines the earliest possibility of a scan seeing a given KV mutation.
      indexer.settings.inmemory_snapshot.moi.interval:
        type: integer
        format: int32
        minimum: 1
        exclusiveMinimum: true
        default: 10
        description: |
          For memory-optimized indexes, the in-memory snapshotting interval (ms).
          This determines the earliest possibility of a scan seeing a given KV mutation.
      indexer.settings.largeSnapshotThreshold:
        type: integer
        format: int32
        default: 200
        description: |
          FIXME: The large snapshot threshold.
      indexer.settings.log_level:
        type: string
        default: info
        description: Indexer logging level.
        enum:
          - silent
          - fatal
          - error
          - warn
          - info
          - verbose
          - timing
          - debug
          - trace
      indexer.settings.maxVbQueueLength:
        type: integer
        format: int32
        default: 0
        description: |
          FIXME: Maximum vBucket queue length.
      indexer.settings.max_array_seckey_size:
        type: integer
        format: int32
        default: 10240
        description: |
          If `indexer.{wbr}settings.{wbr}allow_large_keys` is false, this setting specifies the maximum size for array index keys.

          In Couchbase Server 6.5 and later, the index service does not need to restart when you update this setting.
      indexer.settings.max_cpu_percent:
        type: integer
        format: int32
        default: 0
        description: |
          The CPU capacity that the index service should use (percentage).
          If set to `0`, the indexer will use all CPUs.
      indexer.settings.max_seckey_size:
        type: integer
        format: int32
        default: 4608
        description: |
          If `indexer.{wbr}settings.{wbr}allow_large_keys` is false, this setting specifies the maximum size for index keys.

          In Couchbase Server 6.5 and later, the index service does not need to restart when you update this setting.
      indexer.settings.max_writer_lock_prob:
        type: integer
        format: int32
        default: 20
        description: |
          FIXME: Maximum writer lock prob.
      indexer.settings.memProfFname:
        type: string
        description: |
          FIXME: The name of the file where local memory usage profiling information is captured.
      indexer.settings.memProfile:
        type: boolean
        default: false
        description: |
          FIXME: Whether the index service should capture local memory usage profiling information.
      indexer.settings.memory_quota:
        type: integer
        format: int32
        default: 536870912
        description: How much RAM is allocated to the index service for the current node.
      indexer.settings.minVbQueueLength:
        type: integer
        format: int32
        default: 250
        description: |
          FIXME: Minimum vBucket queue length.
      indexer.settings.moi.debug:
        type: boolean
        default: false
        description: |
          FIXME:
      indexer.settings.moi.persistence_threads:
        type: integer
        format: int32
        default: 1
        description: |
          FIXME: For memory-optimized index storage, the number of persistence threads.
      indexer.settings.moi.recovery.max_rollbacks:
        type: integer
        format: int32
        default: 2
        description: For memory-optimized index storage, the maximum number of committed rollback points.
      indexer.settings.moi.recovery_threads:
        type: integer
        format: int32
        default: 1
        description: |
          FIXME: For memory-optimized index storage, the number of recovery threads.
      indexer.settings.num_replica:
        type: integer
        format: int32
        default: 0
        example: 2
        description: The default number of index-replicas to be created by the index service whenever `CREATE INDEX` is invoked.
      indexer.settings.persisted_snapshot.fdb.interval:
        type: integer
        format: int32
        default: 5000
        minimum: 100
        description: |
          For standard indexes using ForestDB, the persisted snapshotting interval (ms).
          This must be a multiple of the in-memory snapshot interval.
      indexer.settings.persisted_snapshot.interval:
        type: integer
        format: int32
        default: 5000
        minimum: 100
        description: |
          The persisted snapshotting interval (ms).
          This must be a multiple of the in-memory snapshot interval.
      indexer.settings.persisted_snapshot.moi.interval:
        type: integer
        format: int32
        default: 600000
        minimum: 100
        description: |
          For memory-optimized indexes, the persisted snapshotting interval (ms).
          This must be a multiple of the in-memory snapshot interval.
      indexer.settings.persisted_snapshot_init_build.fdb.interval:
        type: integer
        format: int32
        default: 5000
        description: |
          FIXME: For standard indexes using ForestDB, the persisted snapshotting interval for the initial build (ms).
      indexer.settings.persisted_snapshot_init_build.interval:
        type: integer
        format: int32
        default: 5000
        description: |
          FIXME: The persisted snapshotting interval for the initial build (ms).
      indexer.settings.persisted_snapshot_init_build.moi.interval:
        type: integer
        format: int32
        default: 600000
        description: |
          FIXME: For memory-optimized indexes, the persisted snapshotting interval for the initial build (ms).
      indexer.settings.plasma.recovery.max_rollbacks:
        type: integer
        format: int32
        default: 2
        description: For standard indexes using Plasma, the maximum number of committed rollback points.
      indexer.settings.recovery.max_rollbacks:
        type: integer
        format: int32
        default: 2
        description: The maximum number of committed rollback points.
      indexer.settings.scan_getseqnos_retries:
        type: integer
        format: int32
        default: 30
        description: |
          FIXME: Scan get sequence numbers retries.
      indexer.settings.scan_timeout:
        type: integer
        format: int32
        default: 120000
        description: The default timeout for the indexer service.
      indexer.settings.send_buffer_size:
        type: integer
        format: int32
        default: 1024
        description: |
          FIXME: Send buffer size.
      indexer.settings.sliceBufSize:
        type: integer
        format: int32
        default: 50000
        description: |
          FIXME: Slice buffer size.
      indexer.settings.smallSnapshotThreshold:
        type: integer
        format: int32
        default: 30
        description: |
          FIXME: Small snapshot threshold.
      indexer.settings.statsLogDumpInterval:
        type: integer
        format: int32
        default: 60
        description: |
          FIXME: Statistics log dump interval.
      indexer.settings.storage_mode:
        type: string
        default: plasma
        description: |
          The storage mode to be used for the index service on this node.

          '''

          [.edition]#{enterprise}#

          If you are using Enterprise Edition, the possible values are:
          
          plasma::
            Sets the index storage mode to use the Plasma storage engine, which can utilize both memory and persistent storage for index maintenance and index scans.
          memory_optimized::
            Sets the index storage mode to use memory optimized global secondary indexes, which can perform index maintenance and index scan faster at in-memory speeds.

          This setting can only be changed while there are no index nodes in the cluster.
          To change from standard GSI to memory optimized GSI or vice versa, you need to remove all the index service nodes in the cluster.

          '''

          [.edition]#{community}#

          If you are using Community Edition, the default (and only) value is `forestdb`.

          '''

          //
        enum:
          - plasma
          - memory_optimized
          - forestdb
      indexer.settings.storage_mode.disable_upgrade:
        type: boolean
        default: false
        description: |
          FIXME: Whether upgrade of the index storage mode is disabled.
      indexer.settings.wal_size:
        type: integer
        format: int32
        default: 4096
        description: |
          FIXME: Write-ahead log size.
      projector.settings.log_level:
        type: string
        default: info
        description: |
          FIXME: Projector logging level.
      queryport.client.settings.backfillLimit:
        type: integer
        format: int32
        default: 5120
        description: |
          The maximum size of the backfill file (MB).

          * A value of `0` disables backfill.
          * A value of `-1` means the size is unlimited.

          The maximum size is limited only by the available disk space.
      queryport.client.settings.minPoolSizeWM:
        type: integer
        format: int32
        default: 1000
        description: |
          FIXME: Minimum pool size.
      queryport.client.settings.poolOverflow:
        type: integer
        format: int32
        default: 30
        description: Maximum number of connections in a pool.
      queryport.client.settings.poolSize:
        type: integer
        format: int32
        default: 5000
        description: Number of simultaneous active connections connections in a pool.
      queryport.client.settings.relConnBatchSize:
        type: integer
        format: int32
        default: 100
        description: |
          FIXME: Connection batch size.

responses:
  NotFound:
    description: |
      Not found.
      Returns the path with the specified keyspace and index name.

      The keyspace name may be incorrect, the index may not be located on the specified node, or the index may be warming up after a restart.
    schema:
      type: string

securityDefinitions:
  Default:
    type: basic
    description: |
      The Index Settings API supports admin credentials.
      Credentials can be passed via HTTP headers (HTTP basic authentication).

      Users must have Cluster Read and Bucket INDEX List privileges.
      Refer to xref:learn:security/roles.adoc[Roles] for more details.